name: Sales Tax Bot
logo: https://static.thenounproject.com/png/1663712-200.png
scriptId: 11t5dEjkqa2mNzFRBEAK-TxwUkmQlCC_6oJFdvI0tmE8V7CU6bB3ZYBBZ
clientId: 441766948117-9ls7hs1gq9vdh7rc5h30vqhdjob5jlfc.apps.googleusercontent.com
scopes: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.external_request
apiVersion: v2
triggers: onTransactionPosted 
deploymentId: AKfycbxF0YB7SD6f5tfz2Fc5v05QfW7Y65hZr8itiWB2RmpFz-3PvOUn