name: Tax Bot
logo: https://static.thenounproject.com/png/2318500-200.png
# scriptId: 11t5dEjkqa2mNzFRBEAK-TxwUkmQlCC_6oJFdvI0tmE8V7CU6bB3ZYBBZ
# deploymentId: AKfycbxF0YB7SD6f5tfz2Fc5v05QfW7Y65hZr8itiWB2RmpFz-3PvOUn

clientId: 441766948117-9ls7hs1gq9vdh7rc5h30vqhdjob5jlfc.apps.googleusercontent.com
scopes: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.external_request
apiVersion: v3

# webhookUrlDev:  https://bkper-tax-bot.loca.lt
webhookUrlDev: https://us-central1-bkper-tax-trigger.cloudfunctions.net/prod
webhookUrl: https://us-central1-bkper-tax-trigger.cloudfunctions.net/prod

triggers: >
    onTransactionPosted
    onTransactionDeleted
    onTransactionRestored
    onTransactionUpdated

properties: 
    group:
      keys: > 
        tax_rate
        tax_description
      values: >
        ${transaction.description}
        ${account.name}
    account:
      keys: >
        tax_rate
        tax_description
      values: >
        ${transaction.description}
        ${account.name}
    transaction:
      keys: >
        tax_round
        tax_amount
 

